-- MySQL Script generated by MySQL Workbench
-- mar 04 abr 2017 13:13:36 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CasosAcad_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CasosAcad_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CasosAcad_db` DEFAULT CHARACTER SET latin1 ;
USE `CasosAcad_db` ;

-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Proceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Proceso` (
  `idProceso` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProceso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Solicitud` (
  `idSolicitud` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NOT NULL,
  `Solicitante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSolicitud`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Caso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Caso` (
  `idCaso` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `encargado` VARCHAR(45) NOT NULL,
  `idSolicitud` INT(11) NOT NULL,
  `idProceso` INT(11) NOT NULL,
  PRIMARY KEY (`idCaso`),
  INDEX `fk_Caso_1_idx` (`idProceso` ASC),
  INDEX `fk_Caso_2_idx` (`idSolicitud` ASC),
  CONSTRAINT `fk_Caso_1`
    FOREIGN KEY (`idProceso`)
    REFERENCES `CasosAcad_db`.`Proceso` (`idProceso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Caso_2`
    FOREIGN KEY (`idSolicitud`)
    REFERENCES `CasosAcad_db`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Caso_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Caso_Detalle` (
  `idCaso_Detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `idCaso` INT(11) NOT NULL,
  `idProceso_Detalle` INT(11) NOT NULL,
  PRIMARY KEY (`idCaso_Detalle`),
  INDEX `fk_Caso_Detalle_1_idx` (`idCaso` ASC),
  CONSTRAINT `fk_Caso_Detalle_1`
    FOREIGN KEY (`idCaso`)
    REFERENCES `CasosAcad_db`.`Caso` (`idCaso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Caso_Detalle_Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Caso_Detalle_Requisito` (
  `idCaso_Detalle_Requisito` INT(11) NOT NULL AUTO_INCREMENT,
  `idCaso_Detalle` INT(11) NOT NULL,
  `idPaso_Requisito` INT(11) NOT NULL,
  PRIMARY KEY (`idCaso_Detalle_Requisito`),
  INDEX `fk_Caso_Detalle_Requisito_1_idx` (`idCaso_Detalle` ASC),
  CONSTRAINT `fk_Caso_Detalle_Requisito_1`
    FOREIGN KEY (`idCaso_Detalle`)
    REFERENCES `CasosAcad_db`.`Caso_Detalle` (`idCaso_Detalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Caso_Detalle_Requisito_Atestado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Caso_Detalle_Requisito_Atestado` (
  `idCaso_Detalle_Requisito_Atestado` INT(11) NOT NULL AUTO_INCREMENT,
  `idCaso_Detalle_Requisito` INT(11) NOT NULL,
  `documento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCaso_Detalle_Requisito_Atestado`),
  INDEX `fk_Caso_Detalle_Requisito_Atestado_1_idx` (`idCaso_Detalle_Requisito` ASC),
  CONSTRAINT `fk_Caso_Detalle_Requisito_Atestado_1`
    FOREIGN KEY (`idCaso_Detalle_Requisito`)
    REFERENCES `CasosAcad_db`.`Caso_Detalle_Requisito` (`idCaso_Detalle_Requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Tipo_Paso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Tipo_Paso` (
  `idTipo_Paso` INT(11) NOT NULL AUTO_INCREMENT,
  `paso` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `observacion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipo_Paso`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Paso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Paso` (
  `idPaso` INT(11) NOT NULL AUTO_INCREMENT,
  `idTipo_Paso` INT(11) NOT NULL,
  `paso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPaso`),
  INDEX `fk_Paso_1_idx` (`idTipo_Paso` ASC),
  CONSTRAINT `fk_Paso_1`
    FOREIGN KEY (`idTipo_Paso`)
    REFERENCES `CasosAcad_db`.`Tipo_Paso` (`idTipo_Paso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Tipo_Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Tipo_Requisito` (
  `idTipo_Requisito` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT '1',
  `observacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Requisito`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Requisito` (
  `idRequisito` INT(11) NOT NULL AUTO_INCREMENT,
  `idTipo_Requisito` INT(11) NOT NULL,
  `requisito` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `textoPublico` VARCHAR(100) NOT NULL,
  `obligatorio` TINYINT(1) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idRequisito`),
  INDEX `fk_Requisito_1_idx` (`idTipo_Requisito` ASC),
  CONSTRAINT `fk_Requisito_1`
    FOREIGN KEY (`idTipo_Requisito`)
    REFERENCES `CasosAcad_db`.`Tipo_Requisito` (`idTipo_Requisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Paso_Requisito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Paso_Requisito` (
  `idPaso_Requisito` INT(11) NOT NULL AUTO_INCREMENT,
  `idPaso` INT(11) NOT NULL,
  `idRequisito` INT(11) NOT NULL,
  PRIMARY KEY (`idPaso_Requisito`),
  INDEX `fk_Paso_Requisito_1_idx` (`idPaso` ASC),
  INDEX `fk_Paso_Requisito_2_idx` (`idRequisito` ASC),
  CONSTRAINT `fk_Paso_Requisito_1`
    FOREIGN KEY (`idPaso`)
    REFERENCES `CasosAcad_db`.`Paso` (`idPaso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paso_Requisito_2`
    FOREIGN KEY (`idRequisito`)
    REFERENCES `CasosAcad_db`.`Requisito` (`idRequisito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `CasosAcad_db`.`Proceso_Detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CasosAcad_db`.`Proceso_Detalle` (
  `idProceso_Detalle` INT(11) NOT NULL AUTO_INCREMENT,
  `idProceso` INT(11) NOT NULL,
  `idPaso` INT(11) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `solicitante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProceso_Detalle`),
  INDEX `fk_Proceso_Detalle_1_idx` (`idProceso` ASC),
  INDEX `fk_Proceso_Detalle_2_idx` (`idPaso` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
